site_name: Shreya Chaudhary
theme:
  name: material
  icon:
    admonition:
      warning: material/alert
  palette: 
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
